### ISSUE TITLE
Using the ZDKRequests.showRequestCreationWithNavController

### ISSUE THREAD

**Issue by AntonioCuevaUrraco** [sitefinitysteve/nativescript-zendesk#1] opened 2016-01-28 09:42 UTC
I was trying to build up the plugin to use the contact us but I hit the same problem than you did here:
https://github.com/NativeScript/ios-runtime/issues/430
Is there any news about it?
Is there any way to add the window manually to the appdelegate in the meanwhile?

**Comment by sitefinitysteve** [comment] 2016-01-28 17:25
You said you got this to work in that other thread yeah?

...sidenote, Zendesk does have this fixed for their next release, let me poke them again as to when that would be

**Comment by AntonioCuevaUrraco** [comment] 2016-01-29 07:21
That's great, I am checking the request creation(send a ticket) on iOS and it is responding as expected but the attachment button is not there...I wonder if I have to add it somehow or if it is there but got hidden for some reason...Maybe I will create the UI myself in NativeScript and get rid of this problems... I know by experience that calling native components make the navigation stack get corrupted and messy in the android side.

**Comment by sitefinitysteve** [comment] 2016-01-29 12:13
I heard back from Zendesk... They'll have the updated cocoapod up within 2 weeks.  Problem is fixed on their end and even tested in Nativescript.

**Comment by AntonioCuevaUrraco** [comment] 2016-01-29 14:21
I can't make the android side work I have a method quite similar to the one you have commented but don't work. It is like it try to open the new Activity then it get killed automatically and come back to the previous NS Activity(I see the onResume called and nothing else) Did you have more luck with this?

``` ts
exports.openContactZendesk = function (style, successCallback, failCallback){
    if(isInitalized){
       var activity = frameModule.topmost().android.activity;


        var MyZendeskCallback = com.zendesk.service.ZendeskCallback.extend({
            onSuccess: function(args){
                try{ 
                   if(isAnonymous && isUserIdentify){
                        loadAnonUserIdentify();
                    }
                    else if(isAnonymous){
                        loadAnonUser();
                    }

                     var sampleConfig = getConfig();
                     com.zendesk.sdk.network.impl.ZendeskConfig.INSTANCE.setContactConfiguration(sampleConfig);

                     var intent = new android.content.Intent( activity, com.zendesk.sdk.feedback.ui.ContactZendeskActivity.class);
                     application.android.startActivity.startActivity(intent); 


                } catch(args){
                    console.log(args);
                }
            },
            onError: function(error){
                console.log(error);
            }
        });

        var callback = new MyZendeskCallback();

        com.zendesk.sdk.network.impl.ZendeskConfig.INSTANCE.init(activity, 
                                                                account.url,  
                                                                account.appId, 
                                                                account.clientId, 
                                                                callback
                                                            );



    } else{
        console.log("Zendesk account info not initalized, please call the init function on the module");    
    }
}
```

**Comment by sitefinitysteve** [comment] 2016-01-30 23:01
I tried this as well
https://github.com/sitefinitysteve/nativescript-zendesk/blob/master/index.android.js#L63

Yeah so with the latest update to the manifest.xml I see the bar, but when I click the contact "icon" it does what you say... kinda just reloads.

Here's the good news, we have a zendesk enterprise account so I can file a bug and they'll also test with {N} (which is awesome)

I'll get back to you as soon as they let me know, k

**Comment by AntonioCuevaUrraco** [comment] 2016-02-01 08:33
Thank you @sitefinitysteve 
I send them an e-mail with the same issues to let them now that Smarp OY is also expecting them to investigate this and fix it. So let's them check for a while and if nothing can be done, I propose to work on a NativeScript UI to send the tickets and connect it to their request creation methods if possible.

**Comment by sitefinitysteve** [comment] 2016-02-01 16:20
Okay so @schlan (from zendesk) updated the repo will some fixes.  I then refactored it a bit to add in a sample app to use for testing.

Problem though is I can't get the app to run at all on android when I add in the zendesk plugin.  Builds fine, says deployed to device (local or geny), but no app seems to be installed.  Same thing happen to you @AntonioCuevaUrraco any chance?  If I tns plugin remove nativescript-zendesk, the same app loads just fine.

**Comment by schlan** [comment] 2016-02-01 16:34
For me, the Android sample app deployed quite fine to an emulator. Try to use a newly created emulator.  There is still that issue with the FileProvider on the Android, this could cause this problems with deploying the apk.

You also can try to manually run `adb install <generated.apk>` after you build the app.

**Comment by sitefinitysteve** [comment] 2016-02-01 16:38
@schlan Hmm you are right, I guess I was thrown by it not working on my Galaxy AND the emulator... downloaded a new random geny and it deployed just fine.

**Comment by sitefinitysteve** [comment] 2016-02-01 16:44
Contact us now shows up fine!

Suppose now we can start fleshing it out with more of the components

@AntonioCuevaUrraco I'm gonna close the issue as it's pending an iOS zendesk release, not much we can really do at this point but wait.

@schlan Very much thank you for looking into this for us btw

**Closed as completed by sitefinitysteve** 2016-02-01 16:44 UTC

**Comment by sitefinitysteve** [comment] 2016-02-01 19:48
@AntonioCuevaUrraco Zendesk gave us a trial account to test with...I can confirm with the latest changes we can indeed submit tickets now!

**Comment by AntonioCuevaUrraco** [comment] 2016-02-02 07:17
Thant's great :-D  Thank you @sitefinitysteve and @schlan

**Comment by sitefinitysteve** [comment] 2016-02-02 16:15
So good news and bad news... they found a bug in the android widget so if you reply to a ticket, you can't click on the issue in the widget to see the reply.

Identified and fixed though, about 2 weeks for this patch to be included in the next release though (but I suppose we're waiting 2 weeks for iOS anyway)

**Comment by AntonioCuevaUrraco** [comment] 2016-02-03 06:47
:-/ well I think is good if we can release it with all the functions working well, also it is good to know the timeframe more or less as I didn't know before

**Comment by sitefinitysteve** [comment] 2016-02-13 23:07
@AntonioCuevaUrraco The wizards at Zendesk came though, can confirm android and iOS seem solid now :)

**Comment by AntonioCuevaUrraco** [comment] 2016-02-15 13:23
Good news are always nice :-)
